platform :ios, '8.0'
pod 'AFNetworking', '~> 2.4.1'
pod 'AVHexColor', '~> 1.2.0'
pod 'GSProgressHUD', '~> 0.3'
pod 'Reveal-iOS-SDK', '~> 1.0.4'
pod 'SDWebImage', '~> 3.7.1'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
